"""Initial migration

Revision ID: 259da8e99b79
Revises: 
Create Date: 2025-02-16 07:26:14.370781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259da8e99b79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priorityenum'), nullable=True))
    op.create_index(op.f('ix_tasks_completed'), 'tasks', ['completed'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed'), table_name='tasks')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
